###################################################################################################

- name: vault

  hosts: vault

  become: true

  roles:

    - role: consul
    - role: vault

  tags:
    - brain
    - vault

###################################################################################################
