###################################################################################################

- name: vault

  hosts: vault-nodes

  sudo: true

  roles:

    - role: consul
    - role: vault

  tags:
    - brain
    - vault

###################################################################################################
