###################################################################################################

- name: redhat | dependencies

  with_items: '{{ vault_dependencies }}'

  yum: name={{ item }} state=present

  tags:
    - brain
    - vault
    - redhat

###################################################################################################

- name: redhat | allow | http

  when: host_firewall

  firewalld: port={{ vault_http_port }}/tcp
            state=enabled
        permanent=true

  register: config

  tags:
    - brain
    - vault
    - redhat

###################################################################################################

- name: redhat | allow | https

  when: host_firewall

  firewalld: port={{ vault_https_port }}/tcp
            state=enabled
        permanent=true

  register: config

  tags:
    - brain
    - vault
    - redhat

###################################################################################################
